name: Deploy to Oracle Cloud

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy on App Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.APP_SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Clone the repository if it doesn't exist
            if [ ! -d "~/aruga-app/.git" ]; then
              echo "Cloning repository..."
              git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ~/aruga-app
            fi
            
            cd ~/aruga-app
            
            # Pull the latest changes
            echo "Pulling latest code..."
            git pull origin main
            
            # Setup database connection
            echo "Configuring environment..."
            echo "DB_JDBC_URL=jdbc:postgresql://${{ secrets.DB_SERVER_HOST }}:5432/aruga" > .env
            echo "DB_REACTIVE_URL=postgresql://${{ secrets.DB_SERVER_HOST }}:5432/aruga" >> .env
            
            # Redeploy Docker containers (This automatically BUILDS the Backend using the Dockerfile)
            echo "Building backend and deploying containers..."
            docker compose down
            docker compose up -d --build
